device: cuda
model_name: dmcls-graphhb-512-8
seed: 42
train:
  dataset: devmap
  epochs: 1000
  batch_size: 16
  world_size: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  train_from_checkpoint: false
  optimizer: AdamW
  scheduler:
    name: linear
test:
  dataset: devmap
  batch_size: 16
  checkpoint: /p/vast1/LExperts/protorch/runs/20250822134526553068_dmcls-graphhb-512-8/dmcls-graphhb-512-8_0005781_0.83.pt