device: cuda
model_name: vpcls-graphhb-512-8
seed: 42
train:
  dataset: vecparams-x86_64-O3-best_VF_IF
  epochs: 1000
  batch_size: 16
  world_size: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  train_from_checkpoint: false
  optimizer: AdamW
  scheduler:
    name: linear
test:
  dataset: vecparams-x86_64-O3-best_VF_IF
  batch_size: 16
  checkpoint: /p/vast1/LExperts/protorch/runs/20250829121120532455_vpcls-graphhb-512-8/vpcls-graphhb-512-8_0000505_0.85.pt