device: cuda
model_name: vpe2e-512-8-GAT-CLS
seed: 42
train:
  dataset: vecparams-x86_64-O3-best_VF_IF
  epochs: 1000
  batch_size: 16
  world_size: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  train_from_checkpoint: false
  optimizer: AdamW
  scheduler:
    name: linear
test:
  dataset: vecparams-x86_64-O3-best_VF_IF
  batch_size: 16
  checkpoint: /p/vast1/LExperts/protorch/runs/20250901014602345389_vpe2e-512-8-GAT-CLS/vpe2e-512-8-GAT-CLS_0000176_0.84.pt